/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caffe.management.system;

import dao.UserDao;

/**
 *
 * @author tn
 */
public class KennwortAendern extends javax.swing.JFrame {

    public String userEmail;

    /**
     * Creates new form KennwortAendern
     */
    public KennwortAendern() {
        initComponents();
    }

    public KennwortAendern(String email) {
        initComponents();
        userEmail = email;
        btnSpeichern.setEnabled(false);
    }

    public void validateField() {
        String altesKennwort = txtAltesKennwort.getText();
        String neuesKennwort = txtNeuesKennwort.getText();
        String confirmKennwort = txtConfirmKennwort.getText();
        if (!altesKennwort.equals("") && !neuesKennwort.equals("") && neuesKennwort.equals(confirmKennwort)) {
            btnSpeichern.setEnabled(true);
        } else {
            btnSpeichern.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAltesKennwort = new javax.swing.JPasswordField();
        txtNeuesKennwort = new javax.swing.JPasswordField();
        txtConfirmKennwort = new javax.swing.JPasswordField();
        btnSpeichern = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("KENNWORT ÄNDERN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 220, -1));

        jLabel2.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Altes Kennwort");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 120, -1));

        jLabel3.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Neues Kennwort");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 168, 120, 20));

        jLabel4.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Passwort bestätigen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 160, 30));

        txtAltesKennwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAltesKennwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltesKennwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtAltesKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 280, -1));

        txtNeuesKennwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNeuesKennwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNeuesKennwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtNeuesKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 280, -1));

        txtConfirmKennwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtConfirmKennwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmKennwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtConfirmKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 280, -1));

        btnSpeichern.setBackground(new java.awt.Color(24, 153, 67));
        btnSpeichern.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnSpeichern.setForeground(new java.awt.Color(245, 239, 239));
        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, -1));

        jButton3.setBackground(new java.awt.Color(24, 153, 67));
        jButton3.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(245, 239, 239));
        jButton3.setText("Entfernen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 90, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 20, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/SmallBackgroundForUser.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltesKennwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltesKennwortKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtAltesKennwortKeyReleased

    private void txtNeuesKennwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNeuesKennwortKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNeuesKennwortKeyReleased

    private void txtConfirmKennwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmKennwortKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtConfirmKennwortKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new KennwortAendern(userEmail).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        // TODO add your handling code here:
        String altesKennwort = txtAltesKennwort.getText();
        String neuesKennwort = txtNeuesKennwort.getText();
        UserDao.passwortAendern(userEmail, altesKennwort, neuesKennwort);
        setVisible(false);
        new KennwortAendern(userEmail).setVisible(true);
    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KennwortAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KennwortAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KennwortAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KennwortAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KennwortAendern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtAltesKennwort;
    private javax.swing.JPasswordField txtConfirmKennwort;
    private javax.swing.JPasswordField txtNeuesKennwort;
    // End of variables declaration//GEN-END:variables
}
