/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caffe.management.system;

import dao.KategorieDao;
import dao.ProduktDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Kategorie;
import model.Produkt;

/**
 *
 * @author tn
 */
public class Produkt_Anzeigen_Bearbeiten_Löschen extends javax.swing.JFrame {

    /**
     * Creates new form Produkt_Anzeigen_Bearbeiten_Löschen
     */
    public Produkt_Anzeigen_Bearbeiten_Löschen() {
        initComponents();
        btnAktualisieren.setEnabled(false);
        btnEntfernen.setEnabled(false);

    }

    public void validateField() {
        String name = txtName.getText();
        String preis = txtPreis.getText();
        String kategorie = (String) jComboBox1.getSelectedItem();
        if (!name.equals("") && !preis.equals("") && kategorie != null) {
            btnAktualisieren.setEnabled(true);
        } else {
            btnAktualisieren.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPreis = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAktualisieren = new javax.swing.JButton();
        btnEntfernen = new javax.swing.JButton();
        btnLeeren = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produkt anzeigen,bearbeiten & löschen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 360, 30));

        jLabel2.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 70, -1));

        jLabel3.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, -1));

        jLabel4.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategorie");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, -1));

        jLabel5.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Preis");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 70, -1));

        labelid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelid.setForeground(new java.awt.Color(255, 255, 255));
        labelid.setText("00");
        getContentPane().add(labelid, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 330, -1));

        txtPreis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPreis.setForeground(new java.awt.Color(0, 0, 0));
        txtPreis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPreisKeyReleased(evt);
            }
        });
        getContentPane().add(txtPreis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 330, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 330, -1));

        btnAktualisieren.setBackground(new java.awt.Color(255, 255, 255));
        btnAktualisieren.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnAktualisieren.setForeground(new java.awt.Color(0, 0, 0));
        btnAktualisieren.setText("Aktualisieren");
        btnAktualisieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktualisierenActionPerformed(evt);
            }
        });
        getContentPane().add(btnAktualisieren, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnEntfernen.setBackground(new java.awt.Color(255, 255, 255));
        btnEntfernen.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnEntfernen.setForeground(new java.awt.Color(0, 0, 0));
        btnEntfernen.setText("Entfernen");
        btnEntfernen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntfernenActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntfernen, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        btnLeeren.setBackground(new java.awt.Color(255, 255, 255));
        btnLeeren.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnLeeren.setForeground(new java.awt.Color(0, 0, 0));
        btnLeeren.setText("Leeren");
        btnLeeren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerenActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeeren, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 90, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Kategorie", "Preis"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, 500));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 20, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/BlauAdminBackground.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtPreisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPreisKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtPreisKeyReleased

    private void btnAktualisierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktualisierenActionPerformed
        // TODO add your handling code here:
        Produkt produkt = new Produkt();
        int id = Integer.parseInt(labelid.getText());
        produkt.setId(id);
        produkt.setName(txtName.getText());
        produkt.setKategorie((String) jComboBox1.getSelectedItem());
        produkt.setPreis(txtPreis.getText());
        ProduktDao.update(produkt);
        setVisible(false);
        new Produkt_Anzeigen_Bearbeiten_Löschen().setVisible(true);

    }//GEN-LAST:event_btnAktualisierenActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Produkt> list = ProduktDao.getAllRecords();
        Iterator<Produkt> itr = list.iterator();
        while (itr.hasNext()) {
            Produkt produktObj = itr.next();
            dtm.addRow(new Object[]{produktObj.getId(), produktObj.getName(), produktObj.getKategorie(), produktObj.getPreis()});

        }

    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        labelid.setText(id);
        String name = model.getValueAt(index, 1).toString();
        txtName.setText(name);
        String kategorie = model.getValueAt(index, 2).toString();
        String preis = model.getValueAt(index, 3).toString();
        txtPreis.setText(preis);

        btnAktualisieren.setEnabled(true);
        btnEntfernen.setEnabled(true);
        jComboBox1.removeAllItems();
        jComboBox1.addItem(kategorie);
        ArrayList<Kategorie> kategorieList = KategorieDao.getAllRecords();
        Iterator<Kategorie> kategorieItr = kategorieList.iterator();
        while (kategorieItr.hasNext()) {
            Kategorie kategorieObj = kategorieItr.next();
            if (!kategorieObj.getName().equals(kategorie)) {
                jComboBox1.addItem(kategorieObj.getName());
            }

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnEntfernenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntfernenActionPerformed
        // TODO add your handling code here:
        String id = labelid.getText();
        int a = JOptionPane.showConfirmDialog(null, "Möchten Sie dieses Produkt löschen ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            ProduktDao.delete(id);
            setVisible(false);
            new Produkt_Anzeigen_Bearbeiten_Löschen().setVisible(true);

        }

    }//GEN-LAST:event_btnEntfernenActionPerformed

    private void btnLeerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Produkt_Anzeigen_Bearbeiten_Löschen().setVisible(true);

    }//GEN-LAST:event_btnLeerenActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produkt_Anzeigen_Bearbeiten_Löschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produkt_Anzeigen_Bearbeiten_Löschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produkt_Anzeigen_Bearbeiten_Löschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produkt_Anzeigen_Bearbeiten_Löschen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produkt_Anzeigen_Bearbeiten_Löschen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktualisieren;
    private javax.swing.JButton btnEntfernen;
    private javax.swing.JButton btnLeeren;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelid;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPreis;
    // End of variables declaration//GEN-END:variables
}
