/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caffe.management.system;

import dao.UserDao;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author tn
 */
public class Registrieren extends javax.swing.JFrame {

    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String telefonNrPattern = "^[0-9]*$";

    /**
     * Creates new form Registrieren
     */
    public Registrieren() {
        initComponents();
        btnSpeichern.setEnabled(false);

    }

    public void clear() {
        txtName.setText("");
        txtEmail.setText("");
        txtTelefonNr.setText("");
        txtAdresse.setText("");
        txtSicherheitFrage.setText("");
        txtAntwort.setText("");
        txtKennwort.setText("");
        btnSpeichern.setEnabled(false);

    }

    public void validateFields() {
        String name = txtName.getText();
        String email = txtEmail.getText();
        String telefonNr = txtTelefonNr.getText();
        String adresse = txtAdresse.getText();
        String kennwort = txtKennwort.getText();
        String sicherheitFrage = txtSicherheitFrage.getText();
        String antwort = txtAntwort.getText();

        if (!name.equals("") && email.matches(emailPattern) && telefonNr.matches(telefonNrPattern) && telefonNr.length() == 10 && !adresse.equals("") && !kennwort.equals("") && !sicherheitFrage.equals("") && !antwort.equals("")) {
            btnSpeichern.setEnabled(true);
        } else {
            btnSpeichern.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelTelefonNr = new javax.swing.JLabel();
        labelAdresse = new javax.swing.JLabel();
        labelKennwort = new javax.swing.JLabel();
        labelSicherheitFrage = new javax.swing.JLabel();
        labelAntwort = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefonNr = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtSicherheitFrage = new javax.swing.JTextField();
        txtAntwort = new javax.swing.JTextField();
        btnSpeichern = new javax.swing.JButton();
        txtKennwort = new javax.swing.JPasswordField();
        btnEntfernen = new javax.swing.JButton();
        btnBeenden = new javax.swing.JButton();
        btnPasswordVergessen = new javax.swing.JButton();
        btnAnmelden = new javax.swing.JButton();
        txtTitel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrieren");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 160, -1));

        labelName.setBackground(new java.awt.Color(0, 0, 0));
        labelName.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(0, 0, 0));
        labelName.setText("Benutzername");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, 30));

        labelEmail.setBackground(new java.awt.Color(0, 0, 0));
        labelEmail.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(0, 0, 0));
        labelEmail.setText("E-mail");
        getContentPane().add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 100, 30));

        labelTelefonNr.setBackground(new java.awt.Color(0, 0, 0));
        labelTelefonNr.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelTelefonNr.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefonNr.setText("Telefonnummer");
        getContentPane().add(labelTelefonNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 110, 30));

        labelAdresse.setBackground(new java.awt.Color(0, 0, 0));
        labelAdresse.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelAdresse.setForeground(new java.awt.Color(0, 0, 0));
        labelAdresse.setText("Adresse");
        getContentPane().add(labelAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 30));

        labelKennwort.setBackground(new java.awt.Color(0, 0, 0));
        labelKennwort.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelKennwort.setForeground(new java.awt.Color(0, 0, 0));
        labelKennwort.setText("Kennwort");
        getContentPane().add(labelKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 100, 30));

        labelSicherheitFrage.setBackground(new java.awt.Color(0, 0, 0));
        labelSicherheitFrage.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelSicherheitFrage.setForeground(new java.awt.Color(0, 0, 0));
        labelSicherheitFrage.setText("Sicherheitsfrage");
        getContentPane().add(labelSicherheitFrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, 30));

        labelAntwort.setBackground(new java.awt.Color(0, 0, 0));
        labelAntwort.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        labelAntwort.setForeground(new java.awt.Color(0, 0, 0));
        labelAntwort.setText("Antwort");
        getContentPane().add(labelAntwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 110, 30));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 380, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 380, -1));

        txtTelefonNr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTelefonNr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonNrKeyReleased(evt);
            }
        });
        getContentPane().add(txtTelefonNr, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 380, -1));

        txtAdresse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAdresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdresseKeyReleased(evt);
            }
        });
        getContentPane().add(txtAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 380, -1));

        txtSicherheitFrage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSicherheitFrage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSicherheitFrageKeyReleased(evt);
            }
        });
        getContentPane().add(txtSicherheitFrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 380, -1));

        txtAntwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAntwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAntwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtAntwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 380, -1));

        btnSpeichern.setBackground(new java.awt.Color(24, 153, 67));
        btnSpeichern.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        txtKennwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKennwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 380, 30));

        btnEntfernen.setBackground(new java.awt.Color(24, 153, 67));
        btnEntfernen.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnEntfernen.setText("Entfernen");
        btnEntfernen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntfernenActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntfernen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        btnBeenden.setBackground(new java.awt.Color(24, 153, 67));
        btnBeenden.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnBeenden.setText("Beenden");
        btnBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeendenActionPerformed(evt);
            }
        });
        getContentPane().add(btnBeenden, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, -1, -1));

        btnPasswordVergessen.setBackground(new java.awt.Color(24, 153, 67));
        btnPasswordVergessen.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnPasswordVergessen.setText("Kenwwort vergessen ?");
        btnPasswordVergessen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordVergessenActionPerformed(evt);
            }
        });
        getContentPane().add(btnPasswordVergessen, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 190, -1));

        btnAnmelden.setBackground(new java.awt.Color(24, 153, 67));
        btnAnmelden.setFont(new java.awt.Font("Arial Nova Cond", 1, 14)); // NOI18N
        btnAnmelden.setText("Anmelden");
        btnAnmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnmeldenActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnmelden, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, 100, -1));

        txtTitel.setFont(new java.awt.Font("Arial Nova Cond", 1, 36)); // NOI18N
        txtTitel.setForeground(new java.awt.Color(0, 0, 0));
        txtTitel.setText("Cafe Management System");
        getContentPane().add(txtTitel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 510, 60));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 70, 20, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, -3, 20, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/Big background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeendenActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Möchten Sie Wirklich beenden ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {

            System.exit(0);
        }

    }//GEN-LAST:event_btnBeendenActionPerformed

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setName(txtName.getText());
        user.setEmail(txtEmail.getText());
        user.setTelefonNr(txtTelefonNr.getText());
        user.setKennwort(txtKennwort.getText());
        user.setSicherheitFrage(txtSicherheitFrage.getText());
        user.setAntwort(txtAntwort.getText());
        UserDao.save(user);
        clear();

    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void btnEntfernenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntfernenActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnEntfernenActionPerformed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateFields();

    }//GEN-LAST:event_txtNameKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTelefonNrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonNrKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtTelefonNrKeyReleased

    private void txtAdresseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdresseKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtAdresseKeyReleased

    private void txtKennwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKennwortKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtKennwortKeyReleased

    private void txtSicherheitFrageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSicherheitFrageKeyReleased
        // TODO add your handling code here:
        validateFields();

    }//GEN-LAST:event_txtSicherheitFrageKeyReleased

    private void txtAntwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAntwortKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtAntwortKeyReleased

    private void btnAnmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnmeldenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Anmelden().setVisible(true);

    }//GEN-LAST:event_btnAnmeldenActionPerformed

    private void btnPasswordVergessenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordVergessenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new KennwortVergessen().setVisible(true);
    }//GEN-LAST:event_btnPasswordVergessenActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrieren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrieren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnmelden;
    private javax.swing.JButton btnBeenden;
    private javax.swing.JButton btnEntfernen;
    private javax.swing.JButton btnPasswordVergessen;
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelAdresse;
    private javax.swing.JLabel labelAntwort;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelKennwort;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSicherheitFrage;
    private javax.swing.JLabel labelTelefonNr;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtAntwort;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKennwort;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSicherheitFrage;
    private javax.swing.JTextField txtTelefonNr;
    private javax.swing.JLabel txtTitel;
    // End of variables declaration//GEN-END:variables
}
