/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caffe.management.system;

import dao.UserDao;
import model.User;

/**
 *
 * @author tn
 */
public class SicherheitsfrageAendern extends javax.swing.JFrame {

    public String userEmail;

    /**
     * Creates new form SicherheitsfrageAendern
     */
    public SicherheitsfrageAendern() {
        initComponents();
    }

    public SicherheitsfrageAendern(String email) {
        initComponents();
        userEmail = email;
        txtAlteSicherheitfrage.setEditable(false);
        btnSpeichern.setEnabled(false);

    }

    public void validateField() {
        String kennwort = txtKennwort.getText();
        String sicherheitfrage = txtNeueSicherheitfrage.getText();
        String antwort = txtAntwort.getText();

        if (!kennwort.equals("") && !sicherheitfrage.equals("") && !antwort.equals("")) {
            btnSpeichern.setEnabled(true);
        } else {
            btnSpeichern.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAlteSicherheitfrage = new javax.swing.JTextField();
        txtNeueSicherheitfrage = new javax.swing.JTextField();
        txtAntwort = new javax.swing.JTextField();
        txtKennwort = new javax.swing.JPasswordField();
        btnSpeichern = new javax.swing.JButton();
        btnEntfernen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Nova Cond", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SICHERHEITSFRAGE ÄNDERN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 310, 50));

        jLabel2.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Alte Sicherheitsfrage");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, -1));

        jLabel3.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Neue Sicherheitsfrage");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 198, 200, 20));

        jLabel4.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Neue Antwort");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, 30));

        jLabel5.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Kennwort");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 20));

        txtAlteSicherheitfrage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAlteSicherheitfrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlteSicherheitfrageActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlteSicherheitfrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 320, -1));

        txtNeueSicherheitfrage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNeueSicherheitfrage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNeueSicherheitfrageKeyReleased(evt);
            }
        });
        getContentPane().add(txtNeueSicherheitfrage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 320, -1));

        txtAntwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAntwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAntwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtAntwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 320, -1));

        txtKennwort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKennwort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKennwortActionPerformed(evt);
            }
        });
        txtKennwort.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKennwortKeyReleased(evt);
            }
        });
        getContentPane().add(txtKennwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 320, -1));

        btnSpeichern.setBackground(new java.awt.Color(24, 153, 67));
        btnSpeichern.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        btnSpeichern.setForeground(new java.awt.Color(246, 241, 241));
        btnSpeichern.setText("Speichern");
        btnSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeichernActionPerformed(evt);
            }
        });
        getContentPane().add(btnSpeichern, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        btnEntfernen.setBackground(new java.awt.Color(24, 153, 67));
        btnEntfernen.setFont(new java.awt.Font("Arial Nova Cond", 1, 16)); // NOI18N
        btnEntfernen.setForeground(new java.awt.Color(246, 241, 241));
        btnEntfernen.setText("Entfernen");
        btnEntfernen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntfernenActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntfernen, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 20, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/SmallBackgroundForUser.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKennwortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKennwortActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtKennwortActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        User user = UserDao.getSicherheitsfrage(userEmail);
        txtAlteSicherheitfrage.setText(user.getSicherheitFrage());
    }//GEN-LAST:event_formComponentShown

    private void txtNeueSicherheitfrageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNeueSicherheitfrageKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNeueSicherheitfrageKeyReleased

    private void txtAntwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAntwortKeyReleased
        // TODO add your handling code here:
        validateField();

    }//GEN-LAST:event_txtAntwortKeyReleased

    private void txtKennwortKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKennwortKeyReleased
        // TODO add your handling code here:
        validateField();

    }//GEN-LAST:event_txtKennwortKeyReleased

    private void btnSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeichernActionPerformed
        // TODO add your handling code here:
        String kennwort = txtKennwort.getText();
        String sicherheitfrage = txtNeueSicherheitfrage.getText();
        String antwort = txtAntwort.getText();
        UserDao.sicherheitfrageAendern(userEmail, kennwort, sicherheitfrage, antwort);
        setVisible(false);
        new SicherheitsfrageAendern(userEmail).setVisible(true);
    }//GEN-LAST:event_btnSpeichernActionPerformed

    private void btnEntfernenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntfernenActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SicherheitsfrageAendern(userEmail).setVisible(true);
    }//GEN-LAST:event_btnEntfernenActionPerformed

    private void txtAlteSicherheitfrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlteSicherheitfrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlteSicherheitfrageActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SicherheitsfrageAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SicherheitsfrageAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SicherheitsfrageAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SicherheitsfrageAendern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SicherheitsfrageAendern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntfernen;
    private javax.swing.JButton btnSpeichern;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlteSicherheitfrage;
    private javax.swing.JTextField txtAntwort;
    private javax.swing.JPasswordField txtKennwort;
    private javax.swing.JTextField txtNeueSicherheitfrage;
    // End of variables declaration//GEN-END:variables
}
